test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.admin = "john"
    args.sitename = "lemmy website"

    
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.206df4db0b99c52f07ea1a2d5daf799d4b8357fd.name = "Upgrade from 0.15.2~ynh3"